services:
  petclinic:
    image: spring-petclinic:latest
    container_name: petclinic
    ports:
      - "8890:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c 'max_connections=200'

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    depends_on:
      - sonardb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"

  sonardb:
    image: postgres:17.5
    container_name: sonardb
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonardb_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  nexus_data:
  sonardb_data:
