name: CI-CD Spring PetClinic

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-analyze-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_REPO: abd-elrahman-mohamed-anter/jenkins-spring

    steps:
      # 1️⃣ تحميل الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ إعداد Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 3️⃣ Cache لمكتبات Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build بالميفن
      - name: Build project
        run: mvn clean package -DskipTests

      # 5️⃣ تحليل الكود بـ SonarCloud
      - name: Run SonarCloud analysis
        run: mvn sonar:sonar \
             -Dsonar.projectKey=spring-githubactions \
             -Dsonar.organization=abd-elrahman-mohamed-anter \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 6️⃣ تسجيل الدخول في Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7️⃣ بناء Docker image
      - name: Build Docker image
        run: docker build -t $DOCKER_HUB_REPO:latest .

      # 8️⃣ رفع الصورة
      - name: Push Docker image
        run: docker push $DOCKER_HUB_REPO:latest
